# Generated by Django 4.1.5 on 2023-01-27 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('heading', models.CharField(max_length=250, verbose_name='Заголовк')),
                ('slug', models.CharField(max_length=250, unique=True, verbose_name='slug')),
                ('content', models.CharField(max_length=250, verbose_name='Содержимое')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Изображение')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('True', 'положительный'), ('False', 'отрицательный')], default='True', max_length=15)),
                ('view', models.IntegerField(default=0, verbose_name='Просмотры')),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('description_1', models.CharField(max_length=100, verbose_name='Описание 1')),
                ('description_2', models.CharField(max_length=100, verbose_name='Описание 2')),
                ('description_3', models.CharField(max_length=100, verbose_name='Описание 3')),
                ('description_4', models.CharField(max_length=100, verbose_name='Описание 4')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
