# Generated by Django 4.1.5 on 2023-01-27 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templating', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.FileField(upload_to='images/', verbose_name='Изображение'),
        ),
    ]
